// <auto-generated />
using System;
using Ecommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518085112_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Server.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets and devices",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and accessories",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Physical and digital books",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Furniture, tools and decor",
                            IsActive = true,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sporting goods and outdoor gear",
                            IsActive = true,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StripeSessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and foldable design. Compatible with all Bluetooth devices.",
                            ImageBlobName = "3b6b1698-2ada-4c0c-9de9-4b6b406655da.png",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/3b6b1698-2ada-4c0c-9de9-4b6b406655da.png?sv=2025-05-05&se=2036-05-11T11%3A18%3A03Z&sr=b&sp=r&sig=Lk8LNPH9tSUoCMLhPDQ6ncvKgKlrBu0dUr65er5s%2FrY%3D",
                            IsActive = true,
                            Name = "Wireless Noise-Cancelling Headphones",
                            Price = 149.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultra HD 4K smart television with built-in streaming apps, HDR support, and voice remote. Slim bezels and vibrant QLED display.",
                            ImageBlobName = "fd4142c9-c21f-466d-91f8-35254adce270.jpg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/fd4142c9-c21f-466d-91f8-35254adce270.jpg?sv=2025-05-05&se=2036-05-11T10%3A33%3A23Z&sr=b&sp=r&sig=vWlgAJU8lxWRWN7%2Bmx0oM1jQowVtQrgSgRtut9A5NgQ%3D",
                            IsActive = true,
                            Name = "4K Smart TV 55\"",
                            Price = 699.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full-size mechanical keyboard with RGB backlighting, tactile switches, and anti-ghosting. Detachable USB-C cable included.",
                            ImageBlobName = "96f04441-a3f0-4301-bfd4-4777bac1586c.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/96f04441-a3f0-4301-bfd4-4777bac1586c.jpeg?sv=2025-05-05&se=2036-05-11T11%3A15%3A12Z&sr=b&sp=r&sig=UxN2Ug9IqksugoJw13bhcKS%2F2KK3zyx1NE7WA5cs%2F7Q%3D",
                            IsActive = true,
                            Name = "Mechanical Gaming Keyboard",
                            Price = 89.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof (IPX7) compact speaker with 360-degree surround sound and 20-hour battery life. Perfect for outdoor adventures.",
                            ImageBlobName = "c97fd5d4-fb43-440b-ba4b-4603a9bb3638.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/c97fd5d4-fb43-440b-ba4b-4603a9bb3638.jpeg?sv=2025-05-05&se=2036-05-11T11%3A16%3A04Z&sr=b&sp=r&sig=3tao0%2B2ZsO2DqU6oZizsOwpeIYzJEnufUhABn1DuLyo%3D",
                            IsActive = true,
                            Name = "Portable Bluetooth Speaker",
                            Price = 59.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic aluminum laptop stand with 6 adjustable height levels. Compatible with 10–17 inch laptops. Foldable and lightweight.",
                            ImageBlobName = "c462600c-e35c-4043-b6b8-7b36463178d9.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/c462600c-e35c-4043-b6b8-7b36463178d9.jpeg?sv=2025-05-05&se=2036-05-11T11%3A14%3A59Z&sr=b&sp=r&sig=KAojd%2BMwg0uwK2ooB5Jik4bCJP4vMiXVjMLuGm6rzjU%3D",
                            IsActive = true,
                            Name = "Laptop Stand Adjustable",
                            Price = 34.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% organic cotton crew-neck tee in a relaxed fit. Pre-shrunk, machine washable. Available in 12 colours.",
                            ImageBlobName = "5c7cb8fd-91a2-4a28-be9c-8c4f1f5f448b.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/5c7cb8fd-91a2-4a28-be9c-8c4f1f5f448b.jpeg?sv=2025-05-05&se=2036-05-11T11%3A13%3A40Z&sr=b&sp=r&sig=c2Axl3A%2BrPfxcG31gkVSHwEG%2BbjmpyeqPh2MmfJXji4%3D",
                            IsActive = true,
                            Name = "Classic Fit Crew-Neck T-Shirt",
                            Price = 19.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stretch-cotton chinos with a modern slim fit. Five-pocket styling, zip fly. Ideal for smart-casual occasions.",
                            ImageBlobName = "3920d271-da68-4dec-a75b-0cd594725c7c.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/3920d271-da68-4dec-a75b-0cd594725c7c.jpeg?sv=2025-05-05&se=2036-05-11T11%3A17%3A16Z&sr=b&sp=r&sig=rwCh07ePT5YYHXSxHO7i0o%2BDyQCFzMxH5buTUXq%2FaRs%3D",
                            IsActive = true,
                            Name = "Slim Fit Chino Pants",
                            Price = 49.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight packable rain jacket with taped seams, adjustable hood and cuffs, and zippered chest pocket.",
                            ImageBlobName = "a32be3ff-2715-440c-8b8d-40ca878601ec.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/a32be3ff-2715-440c-8b8d-40ca878601ec.jpeg?sv=2025-05-05&se=2036-05-11T11%3A17%3A47Z&sr=b&sp=r&sig=i%2FRUGEG1JrKpgjlFP9g57k6pv903PdfvCvxLryIOd2I%3D",
                            IsActive = true,
                            Name = "Waterproof Hiking Jacket",
                            Price = 89.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Breathable mesh upper with responsive foam midsole. Ideal for road running and gym workouts. Neutral support.",
                            ImageBlobName = "cfa78e29-5f29-4ec4-83ce-0339d8df3ae7.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/cfa78e29-5f29-4ec4-83ce-0339d8df3ae7.jpeg?sv=2025-05-05&se=2036-05-11T11%3A16%3A24Z&sr=b&sp=r&sig=itW%2BBGoyc63acMaI4m5xfKMw6JrJ9%2BR5p%2BBXn3vT3M0%3D",
                            IsActive = true,
                            Name = "Running Sneakers",
                            Price = 74.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A handbook of agile software craftsmanship. Covers writing readable, maintainable code with practical examples in Java.",
                            ImageBlobName = "31cc70a4-4c43-4b5c-9f50-396cd58458d8.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/31cc70a4-4c43-4b5c-9f50-396cd58458d8.jpeg?sv=2025-05-05&se=2036-05-11T11%3A14%3A00Z&sr=b&sp=r&sig=0O6oPZw1f1A8H9C%2FcbYhVFZhVuOny%2FcZ6i%2Fk4n4mZSk%3D",
                            IsActive = true,
                            Name = "Clean Code by Robert C. Martin",
                            Price = 34.99m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeless lessons for software developers by Andrew Hunt and David Thomas. Updated 20th anniversary edition.",
                            ImageBlobName = "ff53c7d0-52de-41c2-93cc-c0e223cb8b0b.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/ff53c7d0-52de-41c2-93cc-c0e223cb8b0b.jpeg?sv=2025-05-05&se=2036-05-11T11%3A17%3A35Z&sr=b&sp=r&sig=W7GP99UeNlQzeiXULJZX3FVvdb14Ei96rJqsTnqVRvc%3D",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 39.99m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep dive into the principles, techniques and tradeoffs of modern distributed data systems by Martin Kleppmann.",
                            ImageBlobName = "d2d19b7a-ee28-4125-82c3-1891a30f0c16.png",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/d2d19b7a-ee28-4125-82c3-1891a30f0c16.png?sv=2025-05-05&se=2036-05-11T11%3A14%3A27Z&sr=b&sp=r&sig=uGLcO0Vyl3QRsOd2FQ26KBlxx%2BLphLp8z8Iaoc3TmpA%3D",
                            IsActive = true,
                            Name = "Designing Data-Intensive Applications",
                            Price = 44.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hand-crafted ceramic dripper with matching server and 50 paper filters. Brews 1–4 cups. Dishwasher safe.",
                            ImageBlobName = "305bd23e-013f-48b1-9de9-d25aee1c3067.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/305bd23e-013f-48b1-9de9-d25aee1c3067.jpeg?sv=2025-05-05&se=2036-05-11T11%3A13%3A30Z&sr=b&sp=r&sig=j8WDkLmGhlNgpVVqY96tXv%2BVFV7xHznx%2FtQpdVVS4OI%3D",
                            IsActive = true,
                            Name = "Ceramic Pour-Over Coffee Set",
                            Price = 42.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tri-ply stainless steel set including saucepans, skillets and stockpot. Oven-safe to 500°F, induction compatible.",
                            ImageBlobName = "f4b8e6f7-558c-43e0-a28a-a950266b4cbb.jpg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/f4b8e6f7-558c-43e0-a28a-a950266b4cbb.jpg?sv=2025-05-05&se=2036-05-11T11%3A18%3A49Z&sr=b&sp=r&sig=HSOb7F59F5hrdPP4y2JnNtNMYRHRHZoep1p7b9K2VG0%3D",
                            IsActive = true,
                            Name = "Stainless Steel Cookware Set (10-Piece)",
                            Price = 199.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hand-poured 8 oz soy wax candle with cotton wick. 45-hour burn time. Made with essential oils. No paraffin.",
                            ImageBlobName = "5c9d1fa8-3f68-4601-afd1-a95a7f73573a.jpeg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/5c9d1fa8-3f68-4601-afd1-a95a7f73573a.jpeg?sv=2025-05-05&se=2036-05-11T11%3A16%3A57Z&sr=b&sp=r&sig=4%2FY0eBkOKJCp%2F58ENbOExRKeL9pqgiV4PDgOF%2FJhftg%3D",
                            IsActive = true,
                            Name = "Scented Soy Candle — Lavender & Vanilla",
                            Price = 16.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Space-saving dumbbell pair with quick-adjust dial system. Replaces 15 sets of weights. Includes storage tray.",
                            ImageBlobName = "d8fc5481-790b-4fc4-ade6-2d511aec4601.jpg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/d8fc5481-790b-4fc4-ade6-2d511aec4601.jpg?sv=2025-05-05&se=2036-05-11T11%3A13%3A19Z&sr=b&sp=r&sig=Hjn9N3g6rPoQVJLhNO0BmihiSMgZp5jyFLJjAgAVFlQ%3D",
                            IsActive = true,
                            Name = "Adjustable Dumbbell Set (5–52.5 lb)",
                            Price = 299.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6mm thick eco-friendly TPE yoga mat with alignment lines. Superior grip, sweat-resistant surface. Includes carry strap.",
                            ImageBlobName = "f380aa1c-f813-4d9e-9edf-06431121497e.jpg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/f380aa1c-f813-4d9e-9edf-06431121497e.jpg?sv=2025-05-05&se=2036-05-11T11%3A18%3A16Z&sr=b&sp=r&sig=%2FwCZCFA8OabgGy0y8uN6Kry%2Bf2VznPIUmkKXI12rwt0%3D",
                            IsActive = true,
                            Name = "Yoga Mat Non-Slip",
                            Price = 29.99m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight MIPS-equipped road helmet with 18 vents, adjustable fit system and removable visor. CE EN 1078 certified.",
                            ImageBlobName = "fcb810d1-fe16-4d65-a31b-03dccecfa553.jpg",
                            ImageUrl = "https://storagecommerceprince.blob.core.windows.net/product-images/fcb810d1-fe16-4d65-a31b-03dccecfa553.jpg?sv=2025-05-05&se=2036-05-11T11%3A14%3A15Z&sr=b&sp=r&sig=R8e77NP4IgbYt2hvULGFnWTNKq%2FF5NCdvBb9TooUZfQ%3D",
                            IsActive = true,
                            Name = "Cycling Helmet",
                            Price = 64.99m,
                            StockQuantity = 90
                        });
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.CartItem", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Order", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Server.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.ProductCategory", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Server.Data.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ecommerce.Server.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ecommerce.Server.Data.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
